WRO_METADATA_FIELDS = [
    'email', 
    'title', 
    'name', 
    'authors',
    'contact_person',
    'contact_person', 
    'contact_person', 
    'contact_person', 
    'dataset_description', 
    'recommended_citation', 
    'did_author_or_contact_organization_collected_the_data', 
    'data_collection_organization', 
    'dataset_language', 
    'publisher', 
    'publication_date', 
    'wrc_project_number', 
    'license', 
    'dataset_license_url', 
    'keywords', 
    'spatial', 
    'wro_theme', 
    'data_structure_category', 
    'uploader_estimation_of_extent_of_processing', 
    'data_classification', 
    'data_reference_date', 
    'data_reference_date', 
    'alternative_identifier', 
    'vertical_extent_datum', 
    'minimum_maximum_extent', 
    'minimum_maximum_extent', 
    'agreement'
    ]

WRO_METADATA_REQUIRED_FIELDS = [] 